# Generated by Django 5.0.2 on 2024-04-24 16:28

import api.models
import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# api.migrations.0001_initial

class Migration(migrations.Migration):

    replaces = []

    dependencies = [
    ]

    def add_default_app(apps, schema_editor):
        # Add a default app for storing dynamic models
        App = apps.get_model("api", "App")
        App.objects.get_or_create(name="api", module="api")

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.app')),
            ],
            options={
                'unique_together': {('app', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255, validators=[api.models.is_valid_field])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.dynamicmodeltable')),
            ],
            options={
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.field')),
            ],
            options={
                'unique_together': {('field', 'name')},
            },
        ),
        migrations.RunPython(
            add_default_app,
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
