services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./src/django_model_builder:/app/
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SECRET_KEY="django-insecure-17b(x%a73quiw-!z2bku_*!cnhb7u^65zzvfv)#_vlv94!zv4h"
      - ALLOWED_HOSTS
      - DEBUG=1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=inproductionthiswouldbemorecomplex
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - db
  db:
    image: postgres:alpine3.19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=inproductionthiswouldbemorecomplex
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

volumes:
  pgdata:
